# 
repo: "https://github.com/agiil/TereEesti"
baseurl: "https://agiil.github.io/TereEesti"
viimatiMuudetud: '26.02.2018'

defaults:
  -
    scope:
      path: "" # Kõik failid
    values:
      layout: "Times"

